# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

target 'CigarettesAndMoneyCounter' do
pod 'Firebase/Core'
pod 'Firebase/AdMob'
end
